namespace DeepwaterEngagementSuite.VoyagePlannerData;

public sealed record VoyageStrategyOptions(
    bool UniqueAmuletClamCross = false,
    bool RareMonstersDrop = true,
    bool RareCurrencyStrongboxEngine = true,
    int SaveSeaPillars = 3,
    bool NoConsumeAnchorfield = false,
    bool CenterSpecialty = false,
    bool AutomaticFocus = true,
    bool ProtectPremiumCharts = true,
    int MaxActiveFocuses = 1,
    double MinimumFocusScore = 1,
    double SecondaryFocusRatio = 0.68,
    double FocusWeightBonus = 0.85,
    double OffFocusMultiplier = 0.25,
    bool ProtectBrineKing = true,
    bool UseBrineKingSynergy = true,
    int SaveBrineKing = 6,
    bool ReserveStrongboxesForValuableCurrency = true,
    int SaveStrongboxes = 9,
    bool ReserveGlobalRareForPremiumStrategies = true,
    int SaveGlobalRare = 9,
    bool DedicatedLostMessageStrategy = true,
    int MinimumLostMessageCharts = 8,
    int SaveLostMessageCharts = 8,
    bool ReserveSulphurForSulphurBorder = true,
    int SaveSulphurCharts = 9,
    int DedicatedStrongboxSetSize = 9,
    int MinimumRareCurrencyStrongboxes = 3,
    int MinimumRareCurrencyGlobalRare = 5,
    int MinimumSulphurCharts = 9,
    int MinimumSulphurPercent = 25,
    bool PreferFastVoyageFillers = true,
    bool DedicatedMessageActive = false,
    bool SulphurStrategyActive = false,
    bool OperativeFleetActive = false,
    bool DivinerFleetActive = false,
    bool FastVoyageActive = false,
    bool GroundLootStrategyActive = false,
    bool SaveKishara = false,
    bool SaveNoEquipment = false,
    bool SaveFractured = false,
    bool SaveGoldenLanterns = false,
    bool SavePantheon = false,
    bool SaveSoulEater = false,
    bool SaveRareFracture = false,
    bool SaveRarePossessed = false)
{
    public static VoyageStrategyOptions AllEnabled { get; } = new();
}
